CREATE TABLE "user"
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT user_pkey
            PRIMARY KEY,
    name        VARCHAR(500) NOT NULL,
    password    VARCHAR(256) NOT NULL,
    login       VARCHAR(256) NOT NULL,
    email       VARCHAR(256) NOT NULL,
    enabled     BOOL,
    company_id  BIGINT
)